// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require("Verifier");

contract('Verifier', async accounts => {
    
    let account1 = accounts[0];
    let account2 = accounts[1];
    let contract = await Verifier.deployed();
    
    describe("Zokrates Verifier", () => {

    it("should show up")
    })
})
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

    
// Test verification with incorrect proof
